default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: smart_market_list_development

test:
  <<: *default
  database: smart_market_list_test

production:
  <<: *default
  database: smart_market_list_production
  username: smart_market_list
  password: <%= ENV['SMART_MARKET_LIST_DATABASE_PASSWORD'] %>